### ISSUE TITLE
CI fails randomly

### ISSUE THREAD

**Issue by rantan** [chaintope/glueby#165]
It looks like connection issue to the MySQL server.

The error is 

```
 1) UtxoProvider behaves like the utxo provider provides utxos to the pool provides utxos to the pool
     Got 0 failures and 2 other errors:
     Shared Example Group: "the utxo provider provides utxos to the pool" called from ./spec/functional/utxo_provider_spec.rb:54

     1.1) Failure/Error: ::ActiveRecord::Base.establish_connection(config)

          ActiveRecord::ConnectionNotEstablished:
            Can't connect to MySQL server on '127.0.0.1:3306' (111)
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/mysql2_adapter.rb:45:in `rescue in new_client'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/mysql2_adapter.rb:39:in `new_client'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/mysql2_adapter.rb:138:in `connect'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/mysql2_adapter.rb:119:in `reconnect!'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract_adapter.rb:533:in `verify!'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `block in checkout_and_verify'
          # ./vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:106:in `run_callbacks'
          # ./vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:824:in `_run_checkout_callbacks'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:930:in `checkout_and_verify'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:800:in `checkout_for_exclusive_access'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:768:in `block (3 levels) in attempt_to_checkout_all_existing_connections'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:764:in `block (2 levels) in attempt_to_checkout_all_existing_connections'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:763:in `loop'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:763:in `block in attempt_to_checkout_all_existing_connections'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:267:in `with_a_bias_for'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:762:in `attempt_to_checkout_all_existing_connections'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:748:in `block in with_exclusively_acquired_all_connections'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:824:in `with_new_connections_blocked'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:747:in `with_exclusively_acquired_all_connections'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:494:in `disconnect'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:516:in `disconnect!'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/pool_config.rb:47:in `block in disconnect!'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/pool_config.rb:43:in `disconnect!'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1152:in `remove_connection_pool'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1052:in `establish_connection'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_handling.rb:52:in `establish_connection'
          # ./spec/spec_helper.rb:84:in `setup_database'
          # ./spec/spec_helper.rb:24:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Mysql2::Error::ConnectionError:
          #   Can't connect to MySQL server on '127.0.0.1:3306' (111)
          #   ./vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:97:in `connect'

     1.2) Failure/Error: connection = ::ActiveRecord::Base.connection

          ActiveRecord::ConnectionNotEstablished:
            No connection pool for 'ActiveRecord::Base' found.
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
          # ./vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/connection_handling.rb:283:in `connection'
          # ./spec/spec_helper.rb:159:in `teardown_database'
          # ./spec/spec_helper.rb:44:in `block (2 levels) in <top (required)>'
```

**Comment by azuchi** [comment]
Fixed by #208.
