### ISSUE TITLE
CI Failure Due to SQLite3 Gem Version Conflict

### ISSUE THREAD

**Issue by rantan** [chaintope/glueby#205]
CI is failing with below error.

```
RSpec::Core::MultipleExceptionError: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1-x86_64-linux-gnu. Make sure all dependencies are added to Gemfile.

No connection pool for 'ActiveRecord::Base' found.

  0) Payment Contract use activerecord wallet adapter bear fees by sender pays TPC to another wallet
     Got 0 failures and 2 other errors:

     0.1) Failure/Error: ::ActiveRecord::Base.establish_connection(config)

          LoadError:
            Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1-x86_64-linux-gnu. Make sure all dependencies are added to Gemfile.
          # ./vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:14:in `<top (required)>'
          # ./vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:333:in `resolve_pool_config'
          # ./vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:134:in `establish_connection'
          # ./vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:53:in `establish_connection'
          # ./spec/spec_helper.rb:93:in `setup_database'
          # ./spec/spec_helper.rb:31:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Gem::LoadError:
          #   can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1-x86_64-linux-gnu. Make sure all dependencies are added to Gemfile.
          #   ./vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:14:in `<top (required)>'

     0.2) Failure/Error: connection = ::ActiveRecord::Base.connection

          ActiveRecord::ConnectionNotEstablished:
            No connection pool for 'ActiveRecord::Base' found.
          # ./vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:243:in `retrieve_connection'
          # ./vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:287:in `retrieve_connection'
          # ./vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:254:in `connection'
          # ./spec/spec_helper.rb:170:in `teardown_database'
          # ./spec/spec_helper.rb:55:in `block (2 levels) in <top (required)>'
1 example, 1 failure, 0 passed
Finished in 0.955374884 seconds
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
Coverage report generated for RSpec to /home/rantan/repos/chaintope/glueby/coverage. 171 / 385 LOC (44.42%) covered.

Process finished with exit code 1
```

**Comment by rantan** [comment]
This line demands sqlite3 version 1.4.x, but the CI uses the latest version 2.0.1.

https://github.com/rails/rails/blob/v7.1.3.2/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L14

It's strange because this code has existed for years, but the CI was successful before.

**Comment by rantan** [comment]
It is because sqlite3 v2.0.0 was released.
